export const EVENT_CHANGE = "EVENT_CHANGE";
export const REGISTER_PHONE_NUMBER = "REGISTER_PHONE_NUMBER";
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";
export const SHOW_FILTER = "SHOW_FILTER";
